schema_version = "0.0.1"

id = "mektools"
version = "1,3,6"
name = "MekTools"
tagline = "This is another extension"
maintainer = "MekuMaki, Shino Mythmaker"
type = "add-on"

website = "https://github.com/MekuMaki/Mektools"

license = [
  "SPDX:AGPL-3.0-or-later",
]

blender_version_min = ""
[permissions]
files = "Import files for most mektoosl functions"
# clipboard = "Copy and paste bone transforms"feature_name = "feature/qol"
feature_patch = ""feature_patch": 53,"
