schema_version = "0.0.1"

id = "mektools"
version = "1.8.10"
name = "MekTools"
feature_patch = "0"
feature_name = "dev"
tagline = "This is another extension"
maintainer = "MekuMaki, Shino Mythmaker"
type = "add-on"

website = "https://github.com/MekuMaki/Mektools"

license = [
  "SPDX:AGPL-3.0-or-later",
]

blender_version_min = "4.2.0"
[permissions]
files = "Import files for most mektoosl functions"
network = "Version checks, can be disabled"
